name: .../anonuser/conda-envs/env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - accelerate==1.10.1
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - asttokens==3.0.0
    - attrs==25.3.0
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - click==8.3.0
    - comm==0.2.3
    - contourpy==1.3.3
    - cycler==0.12.1
    - datasets==4.1.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - dill==0.4.0
    - executing==2.2.1
    - filelock==3.19.1
    - fonttools==4.60.0
    - frozenlist==1.7.0
    - fsspec==2025.9.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - hf-xet==1.1.10
    - huggingface-hub==0.35.0
    - idna==3.10
    - iniconfig==2.3.0
    - ipykernel==6.30.1
    - ipython==9.5.0
    - ipython-pygments-lexers==1.1.1
    - ipywidgets==8.1.7
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.2
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - jupyterlab-widgets==3.0.15
    - kiwisolver==1.4.9
    - markupsafe==3.0.2
    - matplotlib==3.10.6
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - multidict==6.6.4
    - multiprocess==0.70.16
    - nest-asyncio==1.6.0
    - networkx==3.5
    - numpy==2.3.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - packaging==25.0
    - pandas==2.3.2
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.4.0
    - pluggy==1.6.0
    - prompt-toolkit==3.0.52
    - propcache==0.3.2
    - protobuf==6.32.1
    - psutil==7.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==21.0.0
    - pydantic==2.11.9
    - pydantic-core==2.33.2
    - pygments==2.19.2
    - pyparsing==3.2.4
    - pytest==9.0.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==27.1.0
    - regex==2025.9.18
    - requests==2.32.5
    - safetensors==0.6.2
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - seaborn==0.13.2
    - sentry-sdk==2.39.0
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - sympy==1.13.1
    - threadpoolctl==3.6.0
    - tokenizers==0.22.1
    - torch==2.6.0
    - torchvision==0.21.0
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.56.1
    - triton==3.2.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - wandb==0.22.3
    - wcwidth==0.2.13
    - widgetsnbextension==4.0.14
    - xxhash==3.5.0
    - yarl==1.20.1
prefix: /vol/csedu-nobackup/project/tromanski/conda-envs/env
